### PR TITLE
add charts for databend

### PR DESCRIPTION
**Pull request by Junnplus**
Signed-off-by: Ye Sijun <junnplus@gmail.com>

### CODE REVIEW

**Review by ZeaLoVe — COMMENTED** [review]
1、这个helm算一个应用还是两个应用？如果是一个应用，建议不要拆成两个目录维护templates文件和values.yaml
2、meta默认3副本会不会太多了，应该是体验为主的副本1个感觉就够了。

**Review by everpcpc — APPROVED** [review]
:clap:

**Comment by everpcpc** [comment]
> We can consider introduce another chart -- `databend`, which can contain two components at the same time, users can create `databend-meta` and `databend-query` with one yaml file.

I would prefer this one

**Review by ZhiHanZ — APPROVED** [review]
lgtm， please add documentation about helm deployment like simple HA meta service etc, and introduce necessary feature flags

**Pull request merged**
